name: robust_nli
channels:
- soumith
- anaconda
- defaults
dependencies:
- ca-certificates=2018.03.07=0
- nltk=3.3.0=py27_0
- openssl=1.0.2o=h14c3975_1
- pandas=0.23.3=py27h04863e7_0
- python-dateutil=2.7.3=py27_0
- pytz=2018.5=py27_0
- six=1.11.0=py27_1
- blas=1.0=mkl
- cffi=1.10.0=py27_0
- cudatoolkit=9.0=h13b8566_0
- cudnn=7.1.2=cuda9.0_0
- intel-openmp=2018.0.3=0
- libffi=3.2.1=1
- libgcc=5.2.0=0
- libgcc-ng=7.2.0=hdf63c60_3
- libgfortran-ng=7.2.0=hdf63c60_3
- libstdcxx-ng=7.2.0=hdf63c60_3
- mkl=2018.0.3=1
- mkl_fft=1.0.4=py27h4414c95_1
- mkl_random=1.0.1=py27h4414c95_1
- nccl=1.3.5=cuda9.0_0
- ninja=1.8.2=py27h6bb024c_1
- numpy=1.15.0=py27h1b885b7_0
- numpy-base=1.15.0=py27h3dfced4_0
- pip=9.0.1=py27_1
- pycparser=2.18=py27_0
- python=2.7.13=0
- pytorch=0.4.0=py27hdf912b8_0
- readline=6.2=2
- setuptools=27.2.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.11=0
- cuda80=1.0=0
- pip:
  - backports.functools-lru-cache==1.5
  - certifi==2018.4.16
  - chardet==3.0.4
  - conllu==0.8
  - cycler==0.10.0
  - futures==3.0.5
  - goslate==1.5.1
  - idna==2.6
  - kiwisolver==1.0.1
  - matplotlib==2.2.0
  - mkl-fft==1.0.4
  - mkl-random==1.0.1
  - psutil==5.4.5
  - pyparsing==2.2.0
  - python-gnupg==0.3.8
  - requests==2.18.4
  - sklearn==0.0
  - stanfordcorenlp==3.8.0.1
  - subprocess32==3.2.7
  - torch==0.4.0
  - urllib3==1.22

